export type Locale = 'en' | 'ne'

const dictionary: Record<Locale, Record<string, string>> = {
  en: {
    // Navigation
    nav_why: 'Why Farm',
    nav_path: 'Your Path',
    nav_calculator: 'Calculator',
    nav_getstarted: 'Get Started',
    nav_community: 'Community',
    start_now: 'Start Now',
    explore: 'Explore',
    
    // Hero Section
    hero_badge: '🌱 Sustainable • 👥 Community • 📈 Growth',
    hero_title: 'Grow Your Future',
    hero_subtitle: 'in the Heart of Kathmandu Valley',
    hero_description: 'Grow food. Build community. Live sustainably.',
    hero_tagline: 'Your meaningful life starts here.',
    hero_cta_main: 'Begin Your Journey',
    hero_cta_secondary: 'Learn Our Story',
    hero_scroll: 'Discover More',
    
    // Executive Summary
    exec_title: 'Why This Matters',
    exec_subtitle: 'Create a life that feels right. Work that feeds your soul.',
    exec_reason1_title: 'Live with Purpose',
    exec_reason1_desc: 'Connect with the land. Grow food that nourishes body and soul.',
    exec_reason2_title: 'Learn by Doing',
    exec_reason2_desc: 'Start small. Learn organic farming without huge investments. Every harvest is a victory.',
    exec_reason3_title: 'Build Community',
    exec_reason3_desc: 'Join like-minded people. Share knowledge, tools, and the joy of growing together.',
    exec_reason4_title: 'Create Your Home',
    exec_reason4_desc: 'Transform a simple plot into your sanctuary. Where work and passion merge.',
    exec_journey_title: 'Your Journey to a Meaningful Life',
    exec_year1_label: 'Year 1',
    exec_year1_desc: 'Learning & Growing',
    exec_year1_note: 'Investment in your future',
    exec_year2_label: 'Year 2',
    exec_year2_desc: 'Finding Your Rhythm',
    exec_year2_note: 'Your first harvest of success',
    exec_year3_label: 'Year 3',
    exec_year3_desc: 'Living Your Dream',
    exec_year3_note: 'A sustainable, fulfilling life',

    // Context Section
    context_title: 'The Story of Our Land',
    context_subtitle: 'Generations of farmers. Fresh eyes. New chapter.',
    context_current1_title: 'Young People Leaving',
    context_current1_desc: 'Farmers under 35 years of age',
    context_current1_story: 'Most youth are leaving for cities, but the land is calling them back',
    context_current2_title: 'Land Being Lost',
    context_current2_desc: 'Cropland lost to development over 20 years',
    context_current2_story: 'Precious farmland is disappearing, but we can save what remains',
    context_current3_title: 'Families Still Connected',
    context_current3_desc: 'Households still farming in peri-urban areas',
    context_current3_story: 'These families hold the wisdom and traditions we need to preserve',
    context_current4_title: 'Small Plots, Big Dreams',
    context_current4_desc: 'Average family plot size (≈5¼ ropani)',
    context_current4_story: 'Perfect size to start your journey - not too big, not too small',
    context_time_now_title: 'The Time is Now',
    context_time_now_desc: "Everything is aligning for young people who want to live differently. The land is calling, the community is ready, and the world needs what we can grow.",
    context_opp1_title: 'People Want Real Food',
    context_opp1_desc: 'Growing demand for organic, locally-grown food',
    context_opp2_title: 'Land is Available',
    context_opp2_desc: 'Idle plots waiting for passionate farmers',
    context_opp3_title: 'Community is Growing',
    context_opp3_desc: 'Young people choosing sustainable living',
    context_opp4_title: 'Knowledge is Here',
    context_opp4_desc: 'Traditional farming wisdom combined with modern organic techniques',
    context_cta_title: 'Will You Answer the Call?',
    context_cta_desc: 'The land is waiting for someone who will love it, care for it, and grow with it. That someone could be you.',
    context_cta_button: 'Explore Your Options',
    
    // Stats
    stats_families: 'Families ❤️ Land',
    stats_plot: 'Perfect Plot Size 🌱',
    stats_demand: 'Organic Food Demand 📈',
    
    // Action Plan
    action_title: 'Your Journey Begins Here',
    action_subtitle: 'Every great adventure starts with a single step. Here\'s your roadmap to creating the life you\'ve always dreamed of—one that\'s connected to the earth and filled with meaning.',
    action_step1_title: 'Listen to Your Heart',
    action_step1_desc: 'Find a piece of land that speaks to your soul',
    action_step2_title: 'Get to Know Your Land',
    action_step2_desc: 'Test the soil and water to understand what you\'re working with',
    action_step3_title: 'Make Your Agreement',
    action_step3_desc: 'Create a fair arrangement that works for everyone',
    action_step4_title: 'Make It Official',
    action_step4_desc: 'Register your agreement at the local office',
    action_step5_title: 'Build Your Dream Step by Step',
    action_step5_desc: 'Start small and grow as you learn',
    action_step6_title: 'Connect with Your Community',
    action_step6_desc: 'Find people who want what you\'re growing',
    
    // Financial Calculator
    calc_title: 'Your Journey to Financial Freedom',
    calc_subtitle: 'This isn\'t about getting rich—it\'s about building a life where your work sustains you and your family. Use this tool to understand your path to financial independence.',
    calc_land_size: 'Land Size (Ropani)',
    calc_projection: 'Your Journey Projection',
    calc_positive: '📈 Positive',
    calc_investment: '📉 Investment Phase',
    calc_see_plan: 'See Your Action Plan',
    calc_get_help: 'Get Expert Help',
    calc_params_title: 'Your Dream Parameters',
    calc_path_label: 'Your Path',
    calc_annual_land_cost: 'Annual Land Cost (Lakh/Ropani/Year)',
    calc_harvest_potential: 'Your Harvest Potential (Lakh/Year at Full Capacity)',
    calc_annual_costs: 'Annual Living & Farm Costs (Lakh/Year at Full Capacity)',
    calc_initial_setup: 'Initial Setup Investment (Lakh)',
    calc_year1_label: 'Year 1',
    calc_year2_label: 'Year 2',
    calc_year3_label: 'Year 3',
    calc_remember_heading: 'Remember What Matters',
    calc_remember_prefix: 'Remember:',
    calc_remember_body: "These numbers are just a guide. The real value is in the life you'll build— the food you'll grow, the community you'll create, and the peace you'll find in living close to the earth.",
    calc_bullet_follow: 'Follow Your Heart',
    calc_bullet_start_small: 'Start Small, Dream Big',
    calc_bullet_community: 'Build Community',

    // Lease Models
    lease_title: 'Choose Your Path',
    lease_subtitle: "There's no one right way to start your farming journey. Each path offers different benefits and challenges. Choose the one that feels right for your heart and your situation.",
    lease_best_for_label: 'Best for:',
    lease_consider_label: 'Consider:',
    lease_love: "What You'll Love",
    lease_challenges: 'Challenges to Consider',

    // Lease: Simple Lease
    lease_simple_name: 'Simple Land Lease',
    lease_simple_desc: 'Rent a plot and keep everything you grow',
    lease_simple_best: 'Start simple, learn as you go',
    lease_simple_consider: 'Make sure you have a 5-year renewal option',
    lease_simple_pro1: 'Start with minimal commitment',
    lease_simple_pro2: 'Keep all your harvest',
    lease_simple_pro3: 'Simple and straightforward',
    lease_simple_con1: 'Higher upfront costs',
    lease_simple_con2: 'All responsibility is yours',
    lease_simple_con3: 'No shared benefits',

    // Lease: Shared Harvest
    lease_shared_name: 'Shared Harvest (Bataiya)',
    lease_shared_desc: 'Split your harvest with the landowner (usually 50:50)',
    lease_shared_best: 'Start with less money, share the journey',
    lease_shared_consider: 'Be clear about who pays for what',
    lease_shared_pro1: 'Lower upfront costs',
    lease_shared_pro2: 'Shared risk and reward',
    lease_shared_pro3: 'Traditional approach',
    lease_shared_con1: 'Share your harvest',
    lease_shared_con2: 'More complex arrangements',
    lease_shared_con3: 'Potential disagreements',

    // Lease: Lease to Own
    lease_own_name: 'Lease with Future Ownership',
    lease_own_desc: 'Part of your rent goes toward eventually buying the land',
    lease_own_best: 'Test before buying, build equity',
    lease_own_consider: 'Understand the tax implications',
    lease_own_pro1: 'Path to permanent home',
    lease_own_pro2: 'Test before buying',
    lease_own_pro3: 'Build equity over time',
    lease_own_con1: 'More complex structure',
    lease_own_con2: 'Higher total cost',
    lease_own_con3: 'Legal complexity',

    // Lease: Community Farm
    lease_comm_name: 'Community Farm Partnership',
    lease_comm_desc: 'Join with others to farm larger areas together',
    lease_comm_best: 'Community-focused, shared resources',
    lease_comm_consider: 'Clear communication and shared decision-making',
    lease_comm_pro1: 'Shared resources and knowledge',
    lease_comm_pro2: 'Stronger community presence',
    lease_comm_pro3: 'Distributed risk',
    lease_comm_con1: 'Complex coordination',
    lease_comm_con2: 'Shared decision making',
    lease_comm_con3: 'Potential conflicts',

    // Lease: Learning Farm
    lease_learn_name: 'Learning Farm Program',
    lease_learn_desc: 'Work with experienced farmers to learn while you grow',
    lease_learn_best: 'Those who want mentorship and guidance on their journey',
    lease_learn_consider: 'Find the right mentor and clear learning goals',
    lease_learn_pro1: 'Learn from experience',
    lease_learn_pro2: 'Reduced risk',
    lease_learn_pro3: 'Built-in support network',
    lease_learn_con1: 'Less independence',
    lease_learn_con2: 'May take longer to learn',
    lease_learn_con3: 'Dependent on mentor',
    
    // Contact
    contact_title: 'Your Community Awaits',
    contact_subtitle: 'You\'re not alone on this journey. Connect with people who share your dreams, organizations that can help you grow, and places where your harvest will find a home.',
    contact_form_title: 'Get in Touch',
    contact_name: 'Your Name',
    contact_email: 'Email Address',
    contact_message: 'Your Message',
    contact_message_placeholder: 'Tell us about your dreams, questions, or how we can help...',
    contact_send: 'Send Message',
    contact_sending: 'Sending...',
    contact_success: 'Message sent! We\'ll get back to you soon.',
    contact_error: 'Something went wrong. Please try again.',
  },
  ne: {
    // Navigation
    nav_why: 'किन कृषि ?',
    nav_path: 'तपाईंको बाटो',
    nav_calculator: 'क्याल्कुलेटर',
    nav_getstarted: 'सुरु गर्नुस्',
    nav_community: 'समुदाय',
    start_now: 'अहिले सुरु',
    explore: 'अन्वेषण',
    
    // Hero Section
    hero_badge: '🌱 दिगो • 👥 समुदाय • 📈 बृद्धि',
    hero_title: 'आफ्नो भविष्य फुलाउनुस्',
    hero_subtitle: 'काठमाडौं उपत्यकाको मुटुमा',
    hero_description: 'खाना उब्जाउनुस्। समुदाय निर्माण गर्नुस्। दिगो जीवन बिताउनुस्।',
    hero_tagline: 'तपाईंको अर्थपूर्ण जीवन यहाँबाट सुरु हुन्छ।',
    hero_cta_main: 'आफ्नो यात्रा सुरु गर्नुस्',
    hero_cta_secondary: 'हाम्रो कथा जान्नुस्',
    hero_scroll: 'थप पत्ता लगाउनुस्',
    
    // Executive Summary
    exec_title: 'किन यो महत्त्वपूर्ण छ',
    exec_subtitle: 'आफ्नो मनले ठिक ठान्ने जीवन बनाउनुहोस्। आत्मालाई खुवाउने काम।',
    exec_reason1_title: 'उद्देश्यसँग जिउनुस्',
    exec_reason1_desc: 'जमिनसँग जोडिनुस्। शरीर र आत्मालाई खुवाउने खाना उब्जाउनुस्।',
    exec_reason2_title: 'गरेर सिक्नुस्',
    exec_reason2_desc: 'सानोबाट सुरु गर्नुस्। ठूलो लगानी बिना जैविक खेती सिक्नुस्। प्रत्येक बाली एउटा विजय हो।',
    exec_reason3_title: 'समुदाय बनाउनुस्',
    exec_reason3_desc: 'मन मिल्ने मानिसहरूसँग जोडिनुस्। ज्ञान, उपकरण र खुसी बाँड्नुस्।',
    exec_reason4_title: 'आफ्नो घर बनाउनुस्',
    exec_reason4_desc: 'साधारण जमिनलाई आफ्नै आश्रय बनाउनुस्। जहाँ काम र चाहना भेटिन्छ।',
    exec_journey_title: 'अर्थपूर्ण जीवनतर्फको तपाईंको यात्रा',
    exec_year1_label: 'वर्ष १',
    exec_year1_desc: 'सिक्दै र बढ्दै',
    exec_year1_note: 'तपाईंको भविष्यमा लगानी',
    exec_year2_label: 'वर्ष २',
    exec_year2_desc: 'आफ्नो ताल भेट्टाउँदै',
    exec_year2_note: 'सफलताको पहिलो बाली',
    exec_year3_label: 'वर्ष ३',
    exec_year3_desc: 'आफ्नो सपना जिउँदै',
    exec_year3_note: 'दिगो र सन्तोषजनक जीवन',

    // Context Section
    context_title: 'हाम्रो जमिनको कथा',
    context_subtitle: 'पुर्ख्यौली किसान। नयाँ नजर। नयाँ अध्याय।',
    context_current1_title: 'युवाहरू विदेश र शहरतिर',
    context_current1_desc: '३५ वर्ष भन्दा मुनिका किसान',
    context_current1_story: 'धेरै युवा सहरतिर गइरहेका छन्, तर जमिनले तिनलाई फर्काइरहेको छ',
    context_current2_title: 'जमिन हराउँदै',
    context_current2_desc: '२० वर्षमै विकासले हराएको कृषि जमिन',
    context_current2_story: 'अमूल्य जमिन हराइरहेको छ, तर हामी बाँकी जोगाउन सक्छौं',
    context_current3_title: 'परिवारहरू अझै जोडिएका',
    context_current3_desc: 'पेरि-अर्बन क्षेत्रमा खेती गर्ने घरधुरी',
    context_current3_story: 'यी परिवारसँगै हाम्रो परम्परा र ज्ञान सुरक्षित छन्',
    context_current4_title: 'सानो जमिन, ठूला सपना',
    context_current4_desc: 'औसत परिवारिक प्लट साइज (≈५¼ रोपनी)',
    context_current4_story: 'तपाईंको यात्राको उत्तम सुरुवात — न धेरै ठूलो, न धेरै सानो',
    context_time_now_title: 'अहिले नै सही समय',
    context_time_now_desc: 'फरक ढंगले बाँच्न चाहने युवाहरूका लागि सबै कुरा मिल्दैछ। जमिन बोलाइरहेको छ, समुदाय तयार छ, र संसारलाई हामीले उब्जाउने चाहिन्छ।',
    context_opp1_title: 'साँचो खाना चाहिएको छ',
    context_opp1_desc: 'जैविक, स्थानीय खानाको बढ्दो माग',
    context_opp2_title: 'जमिन उपलब्ध छ',
    context_opp2_desc: 'उत्साही किसानको प्रतीक्षामा खाली प्लट',
    context_opp3_title: 'समुदाय बढ्दैछ',
    context_opp3_desc: 'दिगो जीवन रोज्ने युवाहरू',
    context_opp4_title: 'ज्ञान यहीँ छ',
    context_opp4_desc: 'परम्परागत खेती ज्ञान र आधुनिक जैविक विधिको संगम',
    context_cta_title: 'के तपाईं यस आह्वानलाई स्वीकार्नुहुन्छ?',
    context_cta_desc: 'जमिन कसैले माया गर्ने, हेरचाह गर्ने र सँगै बढ्नेको प्रतीक्षामा छ। त्यो कोही तपाईं हुन सक्नुहुन्छ।',
    context_cta_button: 'आफ्ना विकल्पहरू हेर्नुस्',
    
    // Stats
    stats_families: 'परिवारहरू ❤️ जमिन',
    stats_plot: 'उत्तम प्लट साइज 🌱',
    stats_demand: 'जैविक खाना माग 📈',
    
    // Action Plan
    action_title: 'तपाईंको यात्रा यहाँबाट सुरु हुन्छ',
    action_subtitle: 'हरेक महान् साहसिक कार्य एउटै कदमबाट सुरु हुन्छ। तपाईंले सधैं सपना देख्नुभएको जीवन सिर्जना गर्नको लागि यो तपाईंको रोडम्याप हो—जुन पृथ्वीसँग जोडिएको र अर्थले भरिएको छ।',
    action_step1_title: 'आफ्नो मनको कुरा सुन्नुस्',
    action_step1_desc: 'तपाईंको आत्मासँग कुरा गर्ने जमिनको टुक्रा भेट्टाउनुस्',
    action_step2_title: 'आफ्नो जमिनलाई चिन्नुस्',
    action_step2_desc: 'माटो र पानीको जाँच गर्नुस् र के काम गरिरहनुभएको छ भनेर बुझ्नुस्',
    action_step3_title: 'आफ्नो सम्झौता गर्नुस्',
    action_step3_desc: 'सबैका लागि काम गर्ने निष्पक्ष व्यवस्था सिर्जना गर्नुस्',
    action_step4_title: 'यसलाई आधिकारिक बनाउनुस्',
    action_step4_desc: 'स्थानीय कार्यालयमा आफ्नो सम्झौता दर्ता गर्नुस्',
    action_step5_title: 'आफ्नो सपना कदम-कदममा निर्माण गर्नुस्',
    action_step5_desc: 'सानोबाट सुरु गर्नुस् र सिक्दै बढ्नुस्',
    action_step6_title: 'आफ्नो समुदायसँग जोडिनुस्',
    action_step6_desc: 'तपाईंले उब्जाउनुभएको कुरा चाहने मानिसहरूलाई भेट्टाउनुस्',
    
    // Financial Calculator
    calc_title: 'आर्थिक स्वतन्त्रताको लागि तपाईंको यात्रा',
    calc_subtitle: 'यो धनी बन्ने बारेमा होइन—यो तपाईंको काम र परिवारलाई सम्हाल्ने जीवन निर्माण गर्ने बारेमा हो। आर्थिक स्वतन्त्रताको बाटो बुझ्न यो उपकरण प्रयोग गर्नुस्।',
    calc_land_size: 'जमिनको साइज (रोपनी)',
    calc_projection: 'तपाईंको यात्रा प्रक्षेपण',
    calc_positive: '📈 सकारात्मक',
    calc_investment: '📉 लगानी चरण',
    calc_see_plan: 'आफ्नो कार्य योजना हेर्नुस्',
    calc_get_help: 'विशेषज्ञ सहायता लिनुस्',
    calc_params_title: 'तपाईंको सपना परिमितिहरू',
    calc_path_label: 'तपाईंको बाटो',
    calc_annual_land_cost: 'वार्षिक जमिन लागत (लाख/रोपनी/वर्ष)',
    calc_harvest_potential: 'तपाईंको बाली सम्भाव्यता (लाख/वर्ष पूर्ण क्षमतामा)',
    calc_annual_costs: 'वार्षिक जीविकोपार्जन र खेती खर्च (लाख/वर्ष पूर्ण क्षमतामा)',
    calc_initial_setup: 'प्रारम्भिक सेटअप लगानी (लाख)',
    calc_year1_label: 'वर्ष १',
    calc_year2_label: 'वर्ष २',
    calc_year3_label: 'वर्ष ३',
    calc_remember_heading: 'महत्त्वपूर्ण कुरा सम्झनुस्',
    calc_remember_prefix: 'सम्झनुस्:',
    calc_remember_body: 'यी संख्या केवल मार्गदर्शनका लागि हुन्। वास्तविक मूल्य तपाईंले निर्माण गर्ने जीवनमा छ—तपाईंले उब्जाउने खाना, तपाईंले बनाउने समुदाय, र जमिन नजिक बस्दा पाउने शान्तिमा।',
    calc_bullet_follow: 'आफ्नो मन पछ्याउनुस्',
    calc_bullet_start_small: 'सानोबाट सुरु, ठूलो सपना',
    calc_bullet_community: 'समुदाय निर्माण गर्नुस्',

    // Lease Models
    lease_title: 'आफ्नो बाटो छान्नुस्',
    lease_subtitle: 'तपाईंको खेती यात्रा सुरु गर्न एउटामात्र सही बाटो हुँदैन। प्रत्येक बाटोका आफ्नै फाइदा र चुनौतिहरू हुन्छन्। तपाईंको मन र अवस्थासँग मिल्ने बाटो छान्नुस्।',
    lease_best_for_label: 'उत्तम लागि:',
    lease_consider_label: 'विचार गर्नुस्:',
    lease_love: 'तपाईंलाई मन पर्ने कुरा',
    lease_challenges: 'विचार गर्नुपर्ने चुनौतीहरू',

    // Lease: Simple Lease
    lease_simple_name: 'साधारण जमिन भाडा',
    lease_simple_desc: 'एउटा प्लट भाडामा लिएर उब्जाएका सबै तपाईंको',
    lease_simple_best: 'सरल सुरुवात, सिक्दै जाऔं',
    lease_simple_consider: '५ वर्षको नवीकरण विकल्प सुनिश्चित गर्नुस्',
    lease_simple_pro1: 'कम प्रतिबद्धता सहित सुरु',
    lease_simple_pro2: 'उत्पादन सम्पूर्ण तपाईंको',
    lease_simple_pro3: 'सरल र सोझो',
    lease_simple_con1: 'उच्च प्रारम्भिक लागत',
    lease_simple_con2: 'सबै जिम्मेवारी तपाईंमै',
    lease_simple_con3: 'साझा लाभ छैन',

    // Lease: Shared Harvest
    lease_shared_name: 'साझेदारी बाली (बटैया)',
    lease_shared_desc: 'जमिनधनीसँग बाली बाँड्ने (सामान्यतया ५०:५०)',
    lease_shared_best: 'कम पैसामा सुरु, यात्रा साझा',
    lease_shared_consider: 'कोले के तिर्छ भन्ने स्पष्ट हुनुपर्छ',
    lease_shared_pro1: 'कम प्रारम्भिक लागत',
    lease_shared_pro2: 'जोखिम र फाइदा साझेदारी',
    lease_shared_pro3: 'परम्परागत विधि',
    lease_shared_con1: 'बाली बाँड्नुपर्छ',
    lease_shared_con2: 'जटिल व्यवस्था',
    lease_shared_con3: 'मतभेदको सम्भावना',

    // Lease: Lease to Own
    lease_own_name: 'भविष्य स्वामित्व सहितको लिज',
    lease_own_desc: 'भाडाको केही अंशले अन्ततः जमिन किन्न सहयोग गर्छ',
    lease_own_best: 'किन्ने अघि परीक्षण, इक्विटी निर्माण',
    lease_own_consider: 'कर सम्बन्धी प्रभाव बुझ्नुस्',
    lease_own_pro1: 'स्थायी घरतर्फको बाटो',
    lease_own_pro2: 'किन्ने अघि परीक्षण',
    lease_own_pro3: 'समयसँगै इक्विटी निर्माण',
    lease_own_con1: 'अरू जटिल संरचना',
    lease_own_con2: 'समग्र लागत बढी',
    lease_own_con3: 'कानुनी जटिलता',

    // Lease: Community Farm
    lease_comm_name: 'समुदायिक फर्म साझेदारी',
    lease_comm_desc: 'साथीहरूसँग मिलेर ठूलो जमिन खेती गर्नुस्',
    lease_comm_best: 'समुदाय केन्द्रित, साझा स्रोत',
    lease_comm_consider: 'सुस्पष्ट संचार र सह-निर्णय',
    lease_comm_pro1: 'साझा स्रोत र ज्ञान',
    lease_comm_pro2: 'समुदायमा बलियो उपस्थिति',
    lease_comm_pro3: 'जोखिमको वितरण',
    lease_comm_con1: 'समन्वय जटिल',
    lease_comm_con2: 'साझा निर्णय',
    lease_comm_con3: 'संभावित विवाद',

    // Lease: Learning Farm
    lease_learn_name: 'सिकाइ फर्म कार्यक्रम',
    lease_learn_desc: 'अनुभवी किसानसँग काम गर्दै सिक्नुस्',
    lease_learn_best: 'मार्गदर्शन चाहनेका लागि',
    lease_learn_consider: 'उचित मार्गदर्शक र स्पष्ट लक्ष्य खोज्नुस्',
    lease_learn_pro1: 'अनुभवबाट सिकाइ',
    lease_learn_pro2: 'जोखिम घट्ने',
    lease_learn_pro3: 'अन्तर्निर्मित सहयोग सञ्जाल',
    lease_learn_con1: 'कम स्वतन्त्रता',
    lease_learn_con2: 'सिक्न समय लाग्न सक्छ',
    lease_learn_con3: 'मार्गदर्शकमाथि निर्भर',
    
    // Contact
    contact_title: 'तपाईंको समुदायले पर्खिरहेको छ',
    contact_subtitle: 'यो यात्रामा तपाईं एक्लै हुनुहुन्न। तपाईंका सपनाहरू साझा गर्ने मानिसहरू, तपाईंलाई बढ्न मद्दत गर्न सक्ने संस्थाहरू, र तपाईंको फसलले घर पाउने ठाउँहरूसँग जोडिनुस्।',
    contact_form_title: 'सम्पर्कमा रहनुस्',
    contact_name: 'तपाईंको नाम',
    contact_email: 'इमेल ठेगाना',
    contact_message: 'तपाईंको सन्देश',
    contact_message_placeholder: 'तपाईंका सपनाहरू, प्रश्नहरू, वा हामीले कसरी मद्दत गर्न सक्छौं भन्ने बारेमा भन्नुस्...',
    contact_send: 'सन्देश पठाउनुस्',
    contact_sending: 'पठाउँदै...',
    contact_success: 'सन्देश पठाइयो! हामी चाँडै तपाईंलाई फिर्ता सम्पर्क गर्नेछौं।',
    contact_error: 'केही गलत भयो। कृपया पुनः प्रयास गर्नुस्।',
  },
}

export const t = (key: string, locale: Locale = 'en') => {
  return dictionary[locale][key] || dictionary.en[key] || key
} 